export const searchMockData = [
  {
    id: 'artist-omar-courtz',
    type: 'artist',
    title: 'Omar Courtz',
    subtitle: 'Reggaetón / Trap Latino / Experimental',
    meta: '12.4M oyentes mensuales',
    href: '/Artist/1',
    image: 'https://is1-ssl.mzstatic.com/image/thumb/AMCArtistImages221/v4/f5/7c/21/f57c21d6-590a-b07e-1027-e92e6c62cfe6/ami-identity-cee5abcdd03c2870378144a376dce33d-2025-04-18T00-19-44.218Z_cropped.png/486x486bb.png',
  },
  {
      id: 'artist-bad-gyal',
      type: 'artist',
      title: 'Bad Gyal',
      subtitle: 'Dancehall / Reggaetón / Pop Urbano',
      meta: '8.1M oyentes mensuales',
      href: '/Artist/3',  // ← antes era /Artist/2
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6v5uBzxRFt5jpsC33cGOUhBwB7NTSuoBo7A&s',
  },
  
  {
      id: 'artist-twenty-one-pilots',
      type: 'artist',
      title: 'Twenty One Pilots',
      subtitle: 'Alternative Rock / Indie Pop / Electropop',
      meta: '39M oyentes mensuales',
      href: '/Artist/2',
      image: 'https://i.scdn.co/image/ab6761610000517461a7ea26d33ded218cd1e59d',
  },


  {
    id: 'album-psmne',
    type: 'album',
    title: 'POR SI MANANA NO ESTOY',
    subtitle: 'Omar Courtz',
    meta: '2026 • Album',
    href: '/Album/1',
    image: 'https://i1.sndcdn.com/artworks-72d80e69-18fe-4175-b049-3393db902285-0-t500x500.jpg',
  },
  {
    id: 'album-primera-musa',
    type: 'album',
    title: 'PRIMERA MUSA',
    subtitle: 'Omar Courtz',
    meta: '2023 • EP',
    href: '/Album/3',
    image: 'https://is1-ssl.mzstatic.com/image/thumb/Music211/v4/30/0f/48/300f48fd-f560-8aaf-17c1-00a4531ad61a/198588847695.jpg/1200x630bb.jpg',
  },
  {
    id: 'song-comernos',
    type: 'song',
    title: 'COMERNOS',
    subtitle: 'Omar Courtz ft. Bad Gyal',
    meta: '3:42 • 41M plays',
    href: '/Song/15',
    image: 'https://i1.sndcdn.com/artworks-72d80e69-18fe-4175-b049-3393db902285-0-t500x500.jpg',
  },
  {
    id: 'song-monstruo',
    type: 'song',
    title: 'Monstruo',
    subtitle: 'Tainy',
    meta: 'Cancion de la semana',
    href: '/Song/1',
    image: 'https://es.rollingstone.com/wp-content/uploads/2025/10/Tainy-comienza-un-nuevo-capitulo-junto-a-Feid-con-Monstruo-1.jpg',
  },
  {
    id: 'song-what-u-need',
    type: 'song',
    title: 'WHAT U NEED?',
    subtitle: 'Omar Courtz ft. Myke Towers',
    meta: '4:26 • Track destacado',
    href: '/Song/12',
    image: 'https://i1.sndcdn.com/artworks-72d80e69-18fe-4175-b049-3393db902285-0-t500x500.jpg',
  },
  {
    id: 'user-lucia',
    type: 'user',
    title: 'Lucia.mp3',
    subtitle: '',
    meta: '124 resenas publicadas',
    href: '/User/Lucia.mp3',
    image: 'https://avatar.vercel.sh/lucia',
  },
  {
    id: 'user-nicolynz',
    type: 'user',
    title: 'NicoLynz',
    subtitle: 'Top semanal y comentarios rapidos',
    meta: '87 resenas publicadas',
    href: '/User/NicoLynz',
    image: 'https://avatar.vercel.sh/nico',
  },
  {
    id: 'user-sofia',
    type: 'user',
    title: 'Sofia.wav',
    subtitle: 'Produccion, estetica y reseñas largas',
    meta: '61 resenas publicadas',
    href: '/User/Sofia.wav',
    image: 'https://avatar.vercel.sh/sofia',
  },
];